#include <stdint.h>

/* Key names */
struct tVK_names {
	uint8_t id;
	const char *name;
	const char *descr;
};

struct tVK_names vkey_names[] = {
    /*
    {0x01, "", "Left mouse button"},
    {0x02, "", "Right mouse button"},
    {0x03, "", "Control-break processing"},
    {0x04, "", "Middle mouse button"},
    {0x05, "", "X1 mouse button"},
    {0x06, "", "X2 mouse button"},
    */
    {0x07, "", "Undefined"},
    {0x08, "BackSp", "BACKSPACE key"},
    {0x09, "Tab", "TAB key"},
    {0x0A, "", "Reserved"},
    {0x0B, "", "Reserved"},
    {0x0C, "", "CLEAR key"},
    {0x0D, "Enter", "ENTER key"},
    {0x0E, "", "Undefined"},
    {0x0F, "", "Undefined"},
    {0x10, "Shift", "SHIFT key"},
    {0x11, "Ctrl", "CTRL key"},
    {0x12, "Alt", "ALT key"},
    {0x13, "", "PAUSE key"},
    {0x14, "", "CAPS LOCK key"},
    {0x15, "", "IME Kana / Hangul mode"},
    {0x16, "", "IME On"},
    {0x17, "", "IME Junja mode"},
    {0x18, "", "IME final mode"},
    {0x19, "", "IME Hanja / Kanji mode"},
    {0x1A, "", "IME Off"},
    {0x1B, "Esc", "ESC key"},
    {0x1C, "", "IME convert"},
    {0x1D, "", "IME nonconvert"},
    {0x1E, "", "IME accept"},
    {0x1F, "", "IME mode change request"},
    {0x20, "Space", "SPACEBAR"},
    {0x21, "PgUp", "PAGE UP key"},
    {0x22, "PgDn", "PAGE DOWN key"},
    {0x23, "End", "END key"},
    {0x24, "Home", "HOME key"},
    {0x25, "Left", "LEFT ARROW key"},
    {0x26, "Up", "UP ARROW key"},
    {0x27, "Right", "RIGHT ARROW key"},
    {0x28, "Down", "DOWN ARROW key"},
    {0x29, "", "SELECT key"},
    {0x2A, "", "PRINT key"},
    {0x2B, "", "EXECUTE key"},
    {0x2C, "", "PRINT SCREEN key"},
    {0x2D, "Ins", "INS key"},
    {0x2E, "Del", "DEL key"},
    {0x2F, "", "HELP key"},
    {0x30, "0", "0 key"},
    {0x31, "1", "1 key"},
    {0x32, "2", "2 key"},
    {0x33, "3", "3 key"},
    {0x34, "4", "4 key"},
    {0x35, "5", "5 key"},
    {0x36, "6", "6 key"},
    {0x37, "7", "7 key"},
    {0x38, "8", "8 key"},
    {0x39, "9", "9 key"},
    {0x3A, "", "Undefined"},
    {0x3B, "", "Undefined"},
    {0x3C, "", "Undefined"},
    {0x3D, "", "Undefined"},
    {0x3E, "", "Undefined"},
    {0x3F, "", "Undefined"},
    {0x40, "", "Undefined"},
    {0x41, "A", "A key"},
    {0x42, "B", "B key"},
    {0x43, "C", "C key"},
    {0x44, "D", "D key"},
    {0x45, "E", "E key"},
    {0x46, "F", "F key"},
    {0x47, "G", "G key"},
    {0x48, "H", "H key"},
    {0x49, "I", "I key"},
    {0x4A, "J", "J key"},
    {0x4B, "K", "K key"},
    {0x4C, "L", "L key"},
    {0x4D, "M", "M key"},
    {0x4E, "N", "N key"},
    {0x4F, "O", "O key"},
    {0x50, "P", "P key"},
    {0x51, "Q", "Q key"},
    {0x52, "R", "R key"},
    {0x53, "S", "S key"},
    {0x54, "T", "T key"},
    {0x55, "U", "U key"},
    {0x56, "V", "V key"},
    {0x57, "W", "W key"},
    {0x58, "X", "X key"},
    {0x59, "Y", "Y key"},
    {0x5A, "Z", "Z key"},
    {0x5B, "WinL", "Left Windows key"},
    {0x5C, "WinR", "Right Windows key"},
    {0x5D, "", "Applications key"},
    {0x5E, "", "Reserved"},
    {0x5F, "", "Computer Sleep key"},
    {0x60, "Num0", "Numeric keypad 0 key"},
    {0x61, "Num1", "Numeric keypad 1 key"},
    {0x62, "Num2", "Numeric keypad 2 key"},
    {0x63, "Num3", "Numeric keypad 3 key"},
    {0x64, "Num4", "Numeric keypad 4 key"},
    {0x65, "Num5", "Numeric keypad 5 key"},
    {0x66, "Num6", "Numeric keypad 6 key"},
    {0x67, "Num7", "Numeric keypad 7 key"},
    {0x68, "Num8", "Numeric keypad 8 key"},
    {0x69, "Num9", "Numeric keypad 9 key"},
    {0x6A, "", "Multiply key"},
    {0x6B, "", "Add key"},
    {0x6C, "", "Separator key"},
    {0x6D, "", "Subtract key"},
    {0x6E, "", "Decimal key"},
    {0x6F, "", "Divide key"},
    {0x70, "F1", "F1 key"},
    {0x71, "F2", "F2 key"},
    {0x72, "F3", "F3 key"},
    {0x73, "F4", "F4 key"},
    {0x74, "F5", "F5 key"},
    {0x75, "F6", "F6 key"},
    {0x76, "F7", "F7 key"},
    {0x77, "F8", "F8 key"},
    {0x78, "F9", "F9 key"},
    {0x79, "F10", "F10 key"},
    {0x7A, "F11", "F11 key"},
    {0x7B, "F12", "F12 key"},
    {0x7C, "F13", "F13 key"},
    {0x7D, "F14", "F14 key"},
    {0x7E, "F15", "F15 key"},
    {0x7F, "F16", "F16 key"},
    {0x80, "F17", "F17 key"},
    {0x81, "F18", "F18 key"},
    {0x82, "F19", "F19 key"},
    {0x83, "F20", "F20 key"},
    {0x84, "F21", "F21 key"},
    {0x85, "F22", "F22 key"},
    {0x86, "F23", "F23 key"},
    {0x87, "F24", "F24 key"},
    {0x88, "", "Unassigned"},
    {0x89, "", "Unassigned"},
    {0x8A, "", "Unassigned"},
    {0x8B, "", "Unassigned"},
    {0x8C, "", "Unassigned"},
    {0x8D, "", "Unassigned"},
    {0x8E, "", "Unassigned"},
    {0x8F, "", "Unassigned"},
    {0x90, "Num", "NUM LOCK key"},
    {0x91, "Scroll", "SCROLL LOCK key"},
    {0x92, "", "OEM specific"},
    {0x93, "", "OEM specific"},
    {0x94, "", "OEM specific"},
    {0x95, "", "OEM specific"},
    {0x96, "", "OEM specific"},
    {0x97, "", "Unassigned"},
    {0x98, "", "Unassigned"},
    {0x99, "", "Unassigned"},
    {0x9A, "", "Unassigned"},
    {0x9B, "", "Unassigned"},
    {0x9C, "", "Unassigned"},
    {0x9D, "", "Unassigned"},
    {0x9E, "", "Unassigned"},
    {0x9F, "", "Unassigned"},
    {0xA0, "ShiftL", "Left SHIFT key"},
    {0xA1, "ShiftR", "Right SHIFT key"},
    {0xA2, "CtrlL", "Left CONTROL key"},
    {0xA3, "CtrlR", "Right CONTROL key"},
    {0xA4, "MenuL", "Left MENU key"},
    {0xA5, "MenuR", "Right MENU key"},
    {0xA6, "", "Browser Back key"},
    {0xA7, "", "Browser Forward key"},
    {0xA8, "", "Browser Refresh key"},
    {0xA9, "", "Browser Stop key"},
    {0xAA, "", "Browser Search key"},
    {0xAB, "", "Browser Favorites key"},
    {0xAC, "", "Browser Start and Home key"},
    {0xAD, "", "Volume Mute key"},
    {0xAE, "", "Volume Down key"},
    {0xAF, "", "Volume Up key"},
    {0xB0, "", "Next Track key"},
    {0xB1, "", "Previous Track key"},
    {0xB2, "", "Stop Media key"},
    {0xB3, "", "Play/Pause Media key"},
    {0xB4, "", "Start Mail key"},
    {0xB5, "", "Select Media key"},
    {0xB6, "", "Start Application 1 key"},
    {0xB7, "", "Start Application 2 key"},
    {0xB8, "", "Reserved"},
    {0xB9, "", "Reserved"},
    {0xBA, "", "Varies: ;: key"},
    {0xBB, "", "+ key"},
    {0xBC, "", ", key"},
    {0xBD, "", "- key"},
    {0xBE, "", ". key"},
    {0xBF, "", "Varies: /? key"},
    {0xC0, "", "Varies: `~ key"},
    {0xC1, "", "Reserved"},
    {0xC2, "", "Reserved"},
    {0xC3, "", "Reserved"},
    {0xC4, "", "Reserved"},
    {0xC5, "", "Reserved"},
    {0xC6, "", "Reserved"},
    {0xC7, "", "Reserved"},
    {0xC8, "", "Reserved"},
    {0xC9, "", "Reserved"},
    {0xCA, "", "Reserved"},
    {0xCB, "", "Reserved"},
    {0xCC, "", "Reserved"},
    {0xCD, "", "Reserved"},
    {0xCE, "", "Reserved"},
    {0xCF, "", "Reserved"},
    {0xD0, "", "Reserved"},
    {0xD1, "", "Reserved"},
    {0xD2, "", "Reserved"},
    {0xD3, "", "Reserved"},
    {0xD4, "", "Reserved"},
    {0xD5, "", "Reserved"},
    {0xD6, "", "Reserved"},
    {0xD7, "", "Reserved"},
    {0xD8, "", "Unassigned"},
    {0xD9, "", "Unassigned"},
    {0xDA, "", "Unassigned"},
    {0xDB, "", "Varies: [{ key"},
    {0xDC, "", "Varies: \\| key"},
    {0xDD, "", "Varies: ]} key"},
    {0xDE, "", "Varies: '\" key"},
    {0xDF, "", "Varies"},
    {0xE0, "", "Reserved"},
    {0xE1, "", "OEM specific"},
    {0xE2, "", "Angle bracket or the backslash key"},
    {0xE3, "", "OEM specific"},
    {0xE4, "", "OEM specific"},
    {0xE5, "", "IME PROCESS key"},
    {0xE6, "", "OEM specific"},
    //{0xE7, "", "UNICODE"},
    {0xE8, "", "Unassigned"},
    {0xE9, "", "OEM specific"},
    {0xEA, "", "OEM specific"},
    {0xEB, "", "OEM specific"},
    {0xEC, "", "OEM specific"},
    {0xED, "", "OEM specific"},
    {0xEE, "", "OEM specific"},
    {0xEF, "", "OEM specific"},
    {0xF0, "", "OEM specific"},
    {0xF1, "", "OEM specific"},
    {0xF2, "", "OEM specific"},
    {0xF3, "", "OEM specific"},
    {0xF4, "", "OEM specific"},
    {0xF5, "", "OEM specific"},
    {0xF6, "", "Attn key"},
    {0xF7, "", "CrSel key"},
    {0xF8, "", "ExSel key"},
    {0xF9, "", "Erase EOF key"},
    {0xFA, "", "Play key"},
    {0xFB, "", "Zoom key"},
    {0xFC, "", "Reserved"},
    {0xFD, "", "PA1 key"},
    {0xFE, "", "Clear key"},
    {0, NULL, NULL}};
